/**
 * Build-time service worker with hashed precache list.
 * Cache-first for same-origin GETs; cleans old caches on activate.
 * `private.pack` may be cached under an opaque key — never the URL.
 */

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import type { Plugin } from 'vite';

const PRIVATE_FILE = 'private.pack';
const PRIVATE_CACHE_KEY = '__novgorod_private_pack__';
const SW_FILENAME = 'sw.js';

function walkFiles(dir: string, baseDir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walkFiles(full, baseDir));
    } else if (name !== SW_FILENAME) {
      out.push(relative(baseDir, full).split(sep).join('/'));
    }
  }
  return out;
}

function toUrlPath(base: string, relPath: string): string {
  const normalizedBase = base.endsWith('/') ? base : `${base}/`;
  return `${normalizedBase}${relPath.replace(/^\//, '')}`;
}

function renderServiceWorker(
  base: string,
  precacheUrls: string[],
  cacheVersion: string,
): string {
  return `/* Generated by novgorod-pwa-precache — do not edit. */
const CACHE_NAME = ${JSON.stringify(`novgorod-${cacheVersion}`)};
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${JSON.stringify(precacheUrls)};
const PRIVATE_FILE = ${JSON.stringify(PRIVATE_FILE)};
const PRIVATE_CACHE_KEY = ${JSON.stringify(PRIVATE_CACHE_KEY)};

function isPrivatePackUrl(url) {
  try {
    const u = new URL(url);
    return u.pathname.endsWith('/' + PRIVATE_FILE) || u.pathname.endsWith(PRIVATE_FILE);
  } catch {
    return false;
  }
}

function storageKeyFor(request) {
  if (isPrivatePackUrl(request.url)) return PRIVATE_CACHE_KEY;
  return request;
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await cache.addAll(PRECACHE);
      // Prefetch private.pack under an opaque key (URL must not be stored).
      try {
        const privateUrl = new URL(PRIVATE_FILE, self.registration.scope).href;
        const res = await fetch(privateUrl, { cache: 'reload' });
        if (res.ok) {
          await cache.put(PRIVATE_CACHE_KEY, res.clone());
        }
      } catch (_) {
        /* optional asset */
      }
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((k) => k.startsWith('novgorod-') && k !== CACHE_NAME)
          .map((k) => caches.delete(k)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const key = storageKeyFor(req);
      const cached = await cache.match(key);
      if (cached) return cached;

      try {
        const res = await fetch(req);
        if (res.ok) {
          if (isPrivatePackUrl(req.url)) {
            await cache.put(PRIVATE_CACHE_KEY, res.clone());
          } else {
            await cache.put(req, res.clone());
          }
        }
        return res;
      } catch (err) {
        if (isPrivatePackUrl(req.url)) {
          const fallback = await cache.match(PRIVATE_CACHE_KEY);
          if (fallback) return fallback;
        }
        const navFallback = await cache.match(new URL('index.html', self.registration.scope).href);
        if (req.mode === 'navigate' && navFallback) return navFallback;
        throw err;
      }
    })(),
  );
});
`;
}

/** Emit `sw.js` into the build output with a content-hashed cache name. */
export function novgorodPwaPrecache(): Plugin {
  let resolvedBase = '/the-game/';
  let outDir = 'dist';

  return {
    name: 'novgorod-pwa-precache',
    apply: 'build',
    configResolved(config) {
      resolvedBase = config.base;
      outDir = config.build.outDir;
    },
    closeBundle() {
      const absOut = join(process.cwd(), outDir);
      const files = walkFiles(absOut, absOut).sort();
      const publicUrls = files
        .filter((f) => f !== PRIVATE_FILE)
        .map((f) => toUrlPath(resolvedBase, f));

      // Always include shell + manifest even if walk order varies.
      const ensure = [
        toUrlPath(resolvedBase, 'index.html'),
        toUrlPath(resolvedBase, 'manifest.webmanifest'),
      ];
      const precache = [...new Set([...ensure, ...publicUrls])].sort();
      const hash = createHash('sha256')
        .update(precache.join('\n'))
        .digest('hex')
        .slice(0, 12);

      const swSource = renderServiceWorker(resolvedBase, precache, hash);
      writeFileSync(join(absOut, SW_FILENAME), swSource, 'utf8');

      // Stamp hash into a tiny build marker for offline verification scripts.
      writeFileSync(
        join(absOut, 'sw-version.txt'),
        `${hash}\n`,
        'utf8',
      );

      // Prove private.pack exists on disk but is absent from precache URL list.
      try {
        readFileSync(join(absOut, PRIVATE_FILE));
      } catch {
        /* optional */
      }
    },
  };
}
